name: "update subtree"
on:
  workflow_dispatch:

jobs:
  update-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: karlludwigweise/git-subtree@v1
        with:
          pat: ${{ secrets.PAT }}
          repo: https://github.com/harmalpanideloitte/run.git
          action: pull
          prefix: tonomus
          message: Custom Commit Message
      - name: push
        run: git push
