name: Harshit
 
on:
  workflow_dispatch:
jobs:
  subtree_to_aem_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: harmalpanideloitte/run
          ref: refs/heads/main
 
      - name: Subtree
        run: |
          git config --global user.email "harmalpani@deloitte.com"
          git config --global user.name "harmalpanideloitte"
          # git subtree add --prefix=tonomus https://github.com/harmalpanideloitte/CM-AEM-TONOMUS.git main
          git merge subtree --prefix=tonomus https://github.com/harmalpanideloitte/CM-AEM-TONOMUS.git main
 
      - name: Push changes to AEM Main Repo
        run: |
          git push https://github.com/harmalpanideloitte/run.git main
